title: What has Sam been doing lately?
email: sam@1gna.com
signoff: SamAsEnd
description: >
  Some thoughts on software, technology and  
  anything else that's on my mind.
baseurl: "/" 
url: "http://sam.1gna.com"
twitter_username: 4sam21
github_username:  SamAsEnd

markdown: kramdown

plugins:
  - jekyll-feed

disqus:
  shortname: sam-1gna

google_analytics: UA-105095773-1

share: true

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About me
    url:          /about
    external:     false

defaults:
  - values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
